Repository trezor/trezor-firmware, pull requests merged in 2020-08, with the labels that each got.

#1176 python: use stdlib blake2s on python 3.6+
  core/embed/firmware/bootloader_hashes.py
  python/src/trezorlib/_internal/firmware_headers.py
Labels: P4 Low, S4 Low, W1/2, internal, python

#1179 python: Fix UnboundLocalError in trezorctl btc get-address.
  python/CHANGELOG.md
  python/src/trezorlib/__init__.py
  python/src/trezorlib/cli/btc.py
Labels: bug

#1216 legacy/firmware: validate script type only in full-mode known_path_check
  legacy/firmware/crypto.c
Labels: needs backport
