Repository trezor/trezor-firmware, pull requests merged in 2024-03, with the labels that each got.

#3586 docs: hint usage of trezor-user-env
  docs/core/build/emulator.md
  docs/core/emulator/index.md
Labels: docs

#3508 fix(core): fix mouse event processing in the simulator
  core/embed/trezorhal/unix/touch/touch.c
Labels: emulator only

#3584 fix prodtest SBU command documentation
  core/embed/prodtest/README.md
Labels: docs

#3616 fix(core): fixed blurring algo panic in debug mode
  core/embed/rust/src/ui/model_tt/component/homescreen/render.rs
Labels: emulator only

#3621 refactor(core): prepare for non mutable paint function
  core/embed/rust/src/ui/component/text/formatted.rs
  core/embed/rust/src/ui/component/text/op.rs
  core/embed/rust/src/ui/model_tr/component/flow_pages.rs
  core/embed/rust/src/ui/model_tr/component/input_methods/choice.rs
  core/embed/rust/src/ui/model_tt/component/fido.rs
  core/embed/rust/src/ui/model_tt/component/keyboard/passphrase.rs
  core/embed/rust/src/ui/model_tt/component/simple_page.rs
Labels: core

#3618 feat(tests): improve screenshot diffs
  tests/ui_tests/reporting/common.py
  tests/ui_tests/reporting/html.py
  tests/ui_tests/reporting/testreport.js
  tests/ui_tests/reporting/testreport.py
Labels: tests

#3615 refactor(core): remove unused ui components
  core/embed/rust/src/ui/model_tr/component/mod.rs
  core/embed/rust/src/ui/model_tr/component/result_anim.rs
  core/embed/rust/src/ui/model_tr/component/result_popup.rs
Labels: core

#3619 feat(core/emu): handle arrow buttons as swipes
  core/embed/trezorhal/unix/touch/touch.c
Labels: emulator only

#3644 T3T1 Instructions component
  core/embed/rust/src/ui/display/font.rs
  core/embed/rust/src/ui/model_mercury/component/instructions.rs
  core/embed/rust/src/ui/model_mercury/component/mod.rs
  core/embed/rust/src/ui/shape/text.rs
Labels: T3T1

#3653 fix(core): fix build on disc2 model
  core/embed/models/model_D002.h
  core/embed/models/model_D002_layout.c
Labels: hardware only

#3645 T3T1 corner shape
  core/embed/rust/src/ui/geometry.rs
  core/embed/rust/src/ui/shape/corner_highlight.rs
  core/embed/rust/src/ui/shape/mod.rs
Labels: T3T1
