Repository trezor/trezor-firmware, pull requests merged in 2024-09, with the labels that each got.

#4142 fix(core/mercury): show remaining shares
  core/.changelog.d/4142.fixed
  core/embed/rust/src/ui/model_mercury/flow/continue_recovery.rs
  core/embed/rust/src/ui/model_mercury/layout.rs
  core/mocks/generated/trezorui2.pyi
  core/src/apps/management/recovery_device/homescreen.py
  core/src/apps/management/recovery_device/layout.py
  core/src/trezor/ui/layouts/mercury/recovery.py
  core/src/trezor/ui/layouts/tr/recovery.py
  core/src/trezor/ui/layouts/tt/recovery.py
  tests/device_tests/reset_recovery/test_recovery_slip39_advanced.py
  tests/input_flows_helpers.py
  tests/ui_tests/fixtures.json
Labels: T3T1, translations

#4177 chore(core): remove duplicated FlowMsg conversion
  core/embed/rust/src/ui/component/base.rs
  core/embed/rust/src/ui/flow/swipe.rs
Labels: code

#4117 fix(core/ethereum): use BIP44 variant to detect ETH account #
  core/.changelog.d/3627.fixed
  core/src/apps/ethereum/keychain.py
  tests/ui_tests/fixtures.json
Labels: translations

#4218 fix(core): fix slow jpeg decoding
  core/embed/rust/src/io.rs
Labels: core, T2T1

#4221 fix(core): fix handover to bootloader
  core/embed/trezorhal/stm32f4/bootutils.c
Labels: core, T2B1, T2T1

#4228 docs: add Safe 3 and Safe 5 in documentation
  core/README.md
Labels: docs
