Repository trezor/trezor-firmware, pull requests merged in 2024-10, with the labels that each got.

#4232 fix(core): fix interaction-less update
  core/embed/trezorhal/stm32f4/syscall_stubs.c
Labels: core, T2B1, T2T1, T3T1, T3B1

#4247 SLIP-39 extend_mnemonics()
  core/src/trezor/crypto/slip39.py
  core/tests/test_trezor.crypto.slip39.py
Labels: core, R&D

#4267 Framebuffer access control
  core/embed/trezorhal/mpu.h
  core/embed/trezorhal/stm32f4/mpu.c
  core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c
  core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_fb.c
  core/embed/trezorhal/stm32f4/xdisplay/stm32f429i-disc1/display_driver.c
  core/embed/trezorhal/stm32f4/xdisplay/ug-2828/display_driver.c
  core/embed/trezorhal/stm32f4/xdisplay/vg-2864/display_driver.c
  core/embed/trezorhal/stm32u5/mpu.c
  core/embed/trezorhal/stm32u5/xdisplay/stm32u5a9j-dk/display_driver.c
  core/embed/trezorhal/stm32u5/xdisplay/stm32u5a9j-dk/display_fb.c
  core/embed/trezorhal/stm32u5/xdisplay/stm32u5a9j-dk/display_internal.h
Labels: T2B1, T3T1, T3B1

#4278 fix(core): correct swapped F4/U5 reset flags
  core/embed/trezorhal/stm32f4/reset_flags.c
  core/embed/trezorhal/stm32u5/reset_flags.c
Labels: T2B1, T2T1, T3T1, T3B1

#4279 fix(core/rust) Handle touchStop event in brightess dialog
  core/.changelog.d/4261.fixed
  core/embed/rust/src/ui/model_mercury/component/number_input_slider.rs
Labels: T3T1

#4296 fix(core): fix flow_prompt_backup mock
  core/embed/rust/src/ui/model_mercury/layout.rs
  core/mocks/generated/trezorui2.pyi
Labels: code

#4297 fix(cardano): do not show paths while staking
  core/src/apps/cardano/sign_tx/ordinary_signer.py
  core/src/apps/cardano/sign_tx/signer.py
  tests/ui_tests/fixtures.json
Labels: core, altcoin, translations
