Repository trezor/trezor-firmware, pull requests merged in 2024-06, with the labels that each got.

#3894 fix(core/ui): T3T1: improve passphrase prompt
  core/embed/rust/src/ui/model_mercury/layout.rs
  core/src/apps/common/passphrase.py
  core/src/trezor/ui/layouts/mercury/__init__.py
  tests/device_tests/test_session_id_and_passphrase.py
  tests/ui_tests/fixtures.json
Labels: T3T1, translations

#3904 fix(core/ui): T3T1: ethereum signtx hold
  core/embed/rust/src/ui/model_mercury/flow/confirm_action.rs
  core/embed/rust/src/ui/model_mercury/layout.rs
Labels: T3T1

#3937 chore(core): update fixtures.json
  tests/ui_tests/fixtures.json
Labels: translations

#3869 fix(core/embed): fix random delays in usb driver
  core/embed/trezorhal/stm32f4/usb.c
  core/embed/trezorhal/stm32f4/usb_hid-impl.h
  core/embed/trezorhal/stm32f4/usb_webusb-impl.h
Labels: bug, T2B1, T3W1, T2T1, T3T1, T3B1

#3900 Touch driver refactoring
  core/SConscript.bootloader_emu
  core/SConscript.unix
  core/embed/bootloader/bootui.c
  core/embed/bootloader/main.c
  core/embed/bootloader_ci/main.c
  core/embed/extmod/modtrezorio/modtrezorio-poll.h
  core/embed/lib/touch.c
  core/embed/prodtest/.changelog.d/3900.fixed
  core/embed/prodtest/main.c
  core/embed/rust/build.rs
  core/embed/rust/src/trezorhal/io.rs
  core/embed/rust/src/ui/layout/simplified.rs
  core/embed/trezorhal/stm32f4/touch/ft6x36.c
  core/embed/trezorhal/stm32f4/touch/ft6x36.h
  core/embed/trezorhal/stm32f4/touch/stmpe811.c
  core/embed/trezorhal/stm32u5/touch/sitronix.c
  core/embed/trezorhal/touch.h
  core/embed/trezorhal/unix/button.c
  core/embed/trezorhal/unix/touch.c
  core/embed/unix/main.c
  core/site_scons/models/D001/discovery.py
  core/site_scons/models/D002/discovery2.py
  core/site_scons/models/T1B1/emulator.py
  core/site_scons/models/T2B1/emulator.py
  core/site_scons/models/T2T1/emulator.py
  core/site_scons/models/T2T1/trezor_t.py
  core/site_scons/models/T3T1/emulator.py
  core/site_scons/models/T3T1/trezor_t3t1_revE.py
  core/site_scons/models/T3T1/trezor_t3t1_v4.py
Labels: T3W1, T2T1, T3T1

#3903 Haptic driver refactoring
  core/embed/trezorhal/haptic.h
  core/embed/trezorhal/stm32u5/haptic/drv2625/drv2625.c
  core/embed/trezorhal/stm32u5/haptic/drv2625/drv2625.h
Labels: T3T1

#3971 Fix style and unix build
  core/embed/trezorhal/optiga/optiga.c
  core/embed/trezorhal/unix/optiga.c
  tests/ui_tests/fixtures.json
Labels: code, translations
