Repository trezor/trezor-firmware, pull requests merged in 2024-12, with the labels that each got.

#4414 chore: update fixtures for other langs
  tests/ui_tests/fixtures.json
Labels: translations

#4404 Introduce show_danger
  core/embed/rust/librust_qstr.h
  core/embed/rust/src/ui/model_mercury/flow/mod.rs
  core/embed/rust/src/ui/model_mercury/flow/show_danger.rs
  core/embed/rust/src/ui/model_mercury/layout.rs
  core/mocks/generated/trezorui2.pyi
  core/src/trezor/ui/layouts/mercury/__init__.py
  core/src/trezor/ui/layouts/tr/__init__.py
  core/src/trezor/ui/layouts/tt/__init__.py
  tests/ui_tests/fixtures.json
Labels: translations

#4409 chore(core): change display orientation labels [no changelog]
  core/embed/rust/src/translations/generated/translated_string.rs
  core/mocks/trezortranslate_keys.pyi
  core/src/apps/management/apply_settings.py
  core/translations/cs.json
  core/translations/de.json
  core/translations/en.json
  core/translations/es.json
  core/translations/fr.json
  core/translations/it.json
  core/translations/pt.json
  core/translations/signatures.json
  core/translations/tr.json
  tests/ui_tests/fixtures.json
Labels: low hanging fruit, T3T1, translations

#4433 Extend labeling click test into device test
  tests/device_tests/misc/test_msg_enablelabeling.py
  tests/ui_tests/fixtures.json
Labels: translations

#4444 docs(core) Update embedded build instructions, add DISC2 and TrustZone section
  docs/SUMMARY.md
  docs/core/build/embedded.md
  docs/core/misc/disc2.md
  docs/core/misc/trustzone.md
Labels: docs
