Repository trezor/trezor-firmware, pull requests merged in 2024-07, with the labels that each got.

#3968 Fix memory clearing in boardloader
  core/embed/bootloader/main.c
  core/embed/bootloader_ci/main.c
  core/embed/trezorhal/stm32f4/platform.h
  core/embed/trezorhal/stm32f4/util.s
  core/embed/trezorhal/stm32u5/limited_util.s
  core/embed/trezorhal/stm32u5/platform.h
  core/embed/trezorhal/stm32u5/util.s
Labels: T3T1

#3950 Backlight driver refactoring
  core/embed/trezorhal/stm32f4/backlight_pwm.c
  core/embed/trezorhal/stm32f4/backlight_pwm.h
  core/embed/trezorhal/stm32f4/common.c
  core/embed/trezorhal/stm32f4/displays/st7789v.c
  core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c
Labels: T2T1, T3T1

#4035 Avoid overflow in readprotobufint()
  legacy/bootloader/usb.c
Labels: bootloader legacy

#4039 Add rounded overlay to remaining keypads
  core/embed/rust/src/ui/model_mercury/component/keyboard/mnemonic.rs
  core/embed/rust/src/ui/model_mercury/component/keyboard/passphrase.rs
  tests/ui_tests/fixtures.json
Labels: T3T1, translations

#4052 feat(core/mercury): change FW update UI
  core/.changelog.d/4030.added
  core/embed/rust/src/ui/model_mercury/flow/confirm_firmware_update.rs
  core/embed/rust/src/ui/model_mercury/flow/mod.rs
  core/embed/rust/src/ui/model_mercury/layout.rs
  core/embed/rust/src/ui/model_tr/layout.rs
  core/mocks/generated/trezorui2.pyi
Labels: T3T1

#4051 refactor(core/mercury): unify confirm TOS
  core/embed/rust/librust_qstr.h
  core/embed/rust/src/ui/model_mercury/flow/confirm_reset.rs
  core/embed/rust/src/ui/model_mercury/flow/confirm_reset_create.rs
  core/embed/rust/src/ui/model_mercury/flow/confirm_reset_recover.rs
  core/embed/rust/src/ui/model_mercury/flow/mod.rs
  core/embed/rust/src/ui/model_mercury/layout.rs
  core/mocks/generated/trezorui2.pyi
  core/src/trezor/ui/layouts/mercury/__init__.py
Labels: code, T3T1

#4062 chore(core): rename "hidden wallet" -> "passphrase wallet"
  core/embed/rust/librust_qstr.h
  core/embed/rust/src/translations/generated/translated_string.rs
  core/mocks/trezortranslate_keys.pyi
  core/src/apps/common/passphrase.py
  core/tools/translations/rules.json
  core/translations/cs.json
  core/translations/de.json
  core/translations/en.json
  core/translations/es.json
  core/translations/fr.json
  core/translations/order.json
  core/translations/signatures.json
  tests/ui_tests/fixtures.json
Labels: translations

#4071 chore(core/translations): use ASCII apostrophe in French
  core/translations/fr.json
  core/translations/signatures.json
  tests/ui_tests/fixtures.json
Labels: translations

#4066 refactor(core/mercury): init Paragraphs from Vec
  core/embed/rust/src/ui/model_mercury/flow/confirm_set_new_pin.rs
  core/embed/rust/src/ui/model_mercury/flow/prompt_backup.rs
Labels: code, flash reduction, T3T1
