Repository trezor/trezor-firmware, pull requests merged in 2025-08, with the labels that each got.

#5477 Fix suspend loop exit after wakeup from connected power source
  core/embed/sys/suspend/stm32u5/suspend.c
Labels: T3W1

#5413 feat(core): derive entropy from master key
  core/embed/models/D002/vendorheader/vendor_dev_DO_NOT_SIGN.json
  core/embed/models/D002/vendorheader/vendor_prodtest_DO_NOT_SIGN.json
  core/embed/models/D002/vendorheader/vendor_unsafe.json
  core/embed/models/D002/vendorheader/vendorheader_dev_DO_NOT_SIGN_signed_dev.bin
  core/embed/models/D002/vendorheader/vendorheader_dev_DO_NOT_SIGN_unsigned.bin
  core/embed/models/D002/vendorheader/vendorheader_prodtest_DO_NOT_SIGN_signed_dev.bin
  core/embed/models/D002/vendorheader/vendorheader_prodtest_DO_NOT_SIGN_unsigned.bin
  core/embed/models/D002/vendorheader/vendorheader_unsafe_signed_dev.bin
  core/embed/models/D002/vendorheader/vendorheader_unsafe_unsigned.bin
  core/embed/models/T3W1/vendorheader/vendor_dev_DO_NOT_SIGN.json
  core/embed/models/T3W1/vendorheader/vendor_prodtest.json
  core/embed/models/T3W1/vendorheader/vendor_prodtest_DO_NOT_SIGN.json
  core/embed/models/T3W1/vendorheader/vendor_trezor.json
  core/embed/models/T3W1/vendorheader/vendor_trezor_btconly.json
  core/embed/models/T3W1/vendorheader/vendor_unsafe.json
  core/embed/models/T3W1/vendorheader/vendorheader_dev_DO_NOT_SIGN_signed_dev.bin
  core/embed/models/T3W1/vendorheader/vendorheader_dev_DO_NOT_SIGN_unsigned.bin
  core/embed/models/T3W1/vendorheader/vendorheader_prodtest_DO_NOT_SIGN_signed_dev.bin
  core/embed/models/T3W1/vendorheader/vendorheader_prodtest_DO_NOT_SIGN_unsigned.bin
  core/embed/models/T3W1/vendorheader/vendorheader_prodtest_unsigned.bin
  core/embed/models/T3W1/vendorheader/vendorheader_trezor_btconly_unsigned.bin
  core/embed/models/T3W1/vendorheader/vendorheader_trezor_unsigned.bin
  core/embed/models/T3W1/vendorheader/vendorheader_unsafe_signed_dev.bin
  core/embed/models/T3W1/vendorheader/vendorheader_unsafe_unsigned.bin
  core/embed/rust/build.rs
  core/embed/rust/src/trezorhal/storage.rs
  core/embed/sec/entropy/inc/sec/entropy.h
  core/embed/sec/entropy/stm32f4/entropy.c
  core/embed/sec/entropy/stm32u5/entropy.c
  core/embed/sec/entropy/unix/entropy.c
  core/embed/sec/secret/inc/sec/secret_keys.h
  core/embed/sec/secret/stm32u5/secret_keys.c
  core/embed/sys/smcall/stm32/smcall_dispatch.c
  core/embed/sys/smcall/stm32/smcall_stubs.c
  core/embed/sys/smcall/stm32/smcall_verifiers.c
  core/embed/sys/smcall/stm32/smcall_verifiers.h
  core/embed/sys/syscall/stm32/syscall_dispatch.c
  core/embed/sys/syscall/stm32/syscall_stubs.c
  core/embed/sys/syscall/stm32/syscall_verifiers.c
  core/embed/sys/syscall/stm32/syscall_verifiers.h
  core/embed/upymod/modtrezorconfig/modtrezorconfig.c
  core/embed/util/image/image.c
  core/embed/util/image/inc/util/image.h
  core/tools/build_vendorheader
  python/src/trezorlib/firmware/vendor.py
Labels: T3W1

#5513 Eckhart UI: render logo on welcome screen
  core/embed/rust/src/ui/layout_eckhart/bootloader/welcome_screen.rs
  core/embed/rust/src/ui/layout_eckhart/component/mod.rs
  core/embed/rust/src/ui/layout_eckhart/component/welcome_screen.rs
  core/embed/rust/src/ui/layout_eckhart/res/lock_full.toif
  core/embed/rust/src/ui/layout_eckhart/res/warning40.toif
  core/embed/rust/src/ui/layout_eckhart/theme/bootloader.rs
  core/embed/rust/src/ui/layout_eckhart/theme/mod.rs
Labels: T3W1

#5534 chore(core): remove unusued code from BldHeader
  core/embed/rust/src/ui/layout_eckhart/bootloader/bld_header.rs
  core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs
Labels: T3W1

#5543 fix(core/io): Incomplete disabling of haptics
  core/.changelog.d/5532.fixed
  core/embed/io/haptic/drv2625/drv2625.c
Labels: T3T1

#5563 feat(core): add THP transport-level `PING`/`PONG` messages
  core/src/trezor/wire/thp/__init__.py
  core/src/trezor/wire/thp/interface_context.py
  python/src/trezorlib/debuglink.py
  python/src/trezorlib/transport/thp/message_header.py
  python/src/trezorlib/transport/thp/protocol_v2.py
  tests/ui_tests/__init__.py
Labels: translations

#5545 feat(core/eckhart): haptic feedback for HTC animation
  core/embed/rust/src/ui/layout_eckhart/firmware/action_bar.rs
  core/embed/rust/src/ui/layout_eckhart/firmware/hold_to_confirm.rs
Labels: T3W1

#5603 fix(prodtest): fix wpc-info command output
  core/embed/projects/prodtest/.changelog.d/5603.fixed
  core/embed/projects/prodtest/README.md
  core/embed/projects/prodtest/cmd/prodtest_wpc.c
Labels: T3W1

#5604 fix(prodtest): fix secrets-certdev-write arg count check
  core/embed/projects/prodtest/.changelog.d/5604.fixed
  core/embed/projects/prodtest/cmd/prodtest_secrets.c
Labels: T3W1

#5572 feat(core): reimplement THP retransmissions
  core/src/trezor/wire/thp/channel.py
  core/src/trezor/wire/thp/interface_context.py
Labels: core

#5606 Suspend from application layer
  core/embed/upymod/qstrdefsport.h
  core/src/apps/management/pm/suspend.py
  core/src/trezor/ui/__init__.py
Labels: core, T3W1

#5610 fix(core): increase `MAX_SUBSCREENS` a bit
  core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs
Labels: T3W1

#5574 Implement LED switching
  core/embed/io/rgb_led/inc/io/rgb_led.h
  core/embed/io/rgb_led/stm32/rgb_led.c
  core/embed/io/rgb_led/stm32u5/rgb_led_lp.c
  core/embed/io/rgb_led/unix/rgb_led.c
  core/embed/projects/bootloader/main.c
  core/embed/projects/prodtest/main.c
  core/embed/rust/librust_qstr.h
  core/embed/rust/src/translations/generated/translated_string.rs
  core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs
  core/embed/sys/syscall/inc/sys/syscall_numbers.h
  core/embed/sys/syscall/stm32/syscall_dispatch.c
  core/embed/sys/syscall/stm32/syscall_stubs.c
  core/embed/upymod/modtrezorio/modtrezorio-rgb_led.h
  core/embed/upymod/modtrezorio/modtrezorio.c
  core/embed/upymod/modtrezorutils/modtrezorutils.c
  core/mocks/generated/trezorio/__init__.pyi
  core/mocks/generated/trezorio/rgb_led.pyi
  core/mocks/generated/trezorutils.pyi
  core/mocks/trezortranslate_keys.pyi
  core/src/apps/homescreen/device_menu.py
  core/src/boot.py
  core/src/storage/device.py
  core/src/trezor/utils.py
  core/translations/en.json
  core/translations/order.json
  core/translations/signatures.json
Labels: T3W1

#5647 fix(core/eckhart): make scrolling smoother
  core/embed/rust/src/ui/layout_eckhart/firmware/vertical_menu_screen.rs
Labels: T3W1
