Repository trezor/trezor-firmware, pull requests merged in 2025-09, with the labels that each got.

#5680 Power device menu for Eckhart
  core/embed/rust/librust_qstr.h
  core/embed/rust/src/translations/generated/translated_string.rs
  core/embed/rust/src/ui/api/firmware_micropython.rs
  core/embed/rust/src/ui/layout/device_menu_result.rs
  core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs
  core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs
  core/embed/upymod/modtrezorio/modtrezorio-pm.h
  core/mocks/generated/trezorio/pm.pyi
  core/mocks/generated/trezorui_api.pyi
  core/mocks/trezortranslate_keys.pyi
  core/src/apps/homescreen/device_menu.py
  core/translations/en.json
  core/translations/order.json
  core/translations/signatures.json
Labels: T3W1

#5761 chore(core/eckhart): Update regulatory screen
  core/embed/rust/src/ui/layout_eckhart/firmware/regulatory_screen.rs
  core/embed/rust/src/ui/layout_eckhart/res/japan.png
  core/embed/rust/src/ui/layout_eckhart/res/japan.toif
  core/embed/rust/src/ui/layout_eckhart/theme/mod.rs
Labels: T3W1

#5867 fix(core): cache host and app name also at credential-based connection
  core/.changelog.d/5867.fixed
  core/src/apps/thp/pairing.py
  core/src/trezor/wire/thp/interface_context.py
  core/src/trezor/wire/thp/received_message_handler.py
Labels: translations

#5878 fix(core): wait for `_handle_button_requests` only on THP devices
  core/src/trezor/ui/__init__.py
Labels: core, translations
